"""搜索查询和常量"""

SEARCH_QUERIES = [
    {"platform": "boss", "query": "嵌入式实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "C++实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "BSP实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "Linux驱动实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "校招 嵌入式", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "嵌入式实习", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "C++实习", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "BSP实习", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "Linux驱动实习", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "校招 嵌入式", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "嵌入式实习", "city": "101010100", "city_name": "北京"},
    {"platform": "boss", "query": "C++实习", "city": "101010100", "city_name": "北京"},
    {"platform": "boss", "query": "BSP实习", "city": "101010100", "city_name": "北京"},
    {"platform": "boss", "query": "校招 嵌入式", "city": "101010100", "city_name": "北京"},
    {"platform": "boss", "query": "嵌入式实习", "city": "101210100", "city_name": "杭州"},
    {"platform": "boss", "query": "C++实习", "city": "101210100", "city_name": "杭州"},
    {"platform": "boss", "query": "校招 嵌入式", "city": "101210100", "city_name": "杭州"},
    {"platform": "boss", "query": "嵌入式实习", "city": "101270100", "city_name": "成都"},
    {"platform": "boss", "query": "BSP实习", "city": "101270100", "city_name": "成都"},
    {"platform": "boss", "query": "校招 嵌入式", "city": "101270100", "city_name": "成都"},
    {"platform": "boss", "query": "嵌入式开发实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "嵌入式Linux开发", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "BSP工程师", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "Linux驱动开发", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "物联网实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "STM32实习", "city": "101280600", "city_name": "深圳"},
    {"platform": "boss", "query": "嵌入式Linux开发", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "物联网实习", "city": "101020100", "city_name": "上海"},
    {"platform": "boss", "query": "嵌入式Linux开发", "city": "101010100", "city_name": "北京"},
    {"platform": "boss", "query": "物联网实习", "city": "101210100", "city_name": "杭州"},
    {"platform": "boss", "query": "嵌入式Linux开发", "city": "101270100", "city_name": "成都"},
    {"platform": "liepin", "query": "嵌入式实习", "city": "040", "city_name": "深圳"},
    {"platform": "liepin", "query": "BSP实习", "city": "040", "city_name": "深圳"},
    {"platform": "liepin", "query": "Linux驱动实习", "city": "040", "city_name": "深圳"},
    {"platform": "lagou", "query": "嵌入式实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "lagou", "query": "C++实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "lagou", "query": "物联网实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "niuke", "query": "嵌入式实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "niuke", "query": "BSP实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "zhaopin", "query": "嵌入式实习", "city": "763", "city_name": "深圳"},
    {"platform": "zhaopin", "query": "C++实习", "city": "763", "city_name": "深圳"},
    {"platform": "zhaopin", "query": "BSP实习", "city": "763", "city_name": "深圳"},
    {"platform": "shixiseng", "query": "嵌入式实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "shixiseng", "query": "C++实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "shixiseng", "query": "BSP实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "shixiseng", "query": "Linux驱动实习", "city": "深圳", "city_name": "深圳"},
    {"platform": "shixiseng", "query": "嵌入式开发", "city": "深圳", "city_name": "深圳"},
]

SCORE_THRESHOLD = 80
DATA_DIR = "data"
DATA_FILE = "data/seen_jobs.json"
